[package]

name = "getting-started-spinning-square"
version = "0.1.0"
authors = [
  "Test Taro <testotaro@testotaro.com>"
  ]

[[bin]]
name = "spinning-square"

[dependencies]
piston = "0.19.0"
piston2d-graphics = "0.16.0"
pistoncore-glutin_window = "0.22.0"
piston2d-opengl_graphics = "0.25.0"

