BIN     = build/hello_triangle
CC      = g++
FLAGS   = -Wall -pedantic -std=c++11
INC     = -I ../common/include
LOC_LIB = ../common/lib/libglfw3.a ../common/lib/libGLEW.a
SYS_LIB = -lGL -lGLU -lX11 -lXi -lXrandr -lXxf86vm -lXinerama -lXcursor -lrt -lm -lpthread
SRC     = main.c

all:
	${CC} ${FLAGS} -o ${BIN} ${SRC} ${INC} ${LOC_LIB} ${SYS_LIB}
